---
id: azusa_colors
tags: []
version: 1.0.0
licenses: []
author:
  markup_language: markdown
  name: MATSUMOTO, Katsuyoshi
  email: work@katsoyshi.org
  rubygems_user: 
  slideshare_user: 
  speaker_deck_user: 
